"""Constants shared by Despatch modules."""

PRODUCT_NAME = "Despatch"
PRODUCT_VERSION = "0.1.0"
PRODUCT_DESCRIPTION = "Application launcher for Envoy-managed environments"
ORGANIZATION_NAME = "gtvfx-contrib"
ORGANIZATION_DOMAIN = "gtvfx-contrib.github.io"
DOCUMENTATION_URL = "https://gtvfx-contrib.github.io/gt-despatch/"
DOCUMENTATION_IDLE_TIMEOUT_SECONDS = 2 * 60 * 60

MANIFEST_FILENAME = "despatch.json"
MANIFEST_SCHEMA_VERSION = 1
RESOURCE_ICONS_DIRECTORY = "resources/icons"
SETTINGS_SCHEMA_VERSION = 1
MAX_RECENT_APPLICATIONS = 20

DEFAULT_STACK_REFRESH_INTERVAL_SECONDS = 5 * 60
MINIMUM_STACK_REFRESH_INTERVAL_SECONDS = 60
MAXIMUM_STACK_REFRESH_INTERVAL_SECONDS = 60 * 60
STACK_PROBE_SLOW_SECONDS = 15
STACK_CHANGE_CONFIRMATION_SECONDS = 2
STACK_PROBE_FAILURE_WARNING_COUNT = 2
STACK_PROBE_MAX_BACKOFF_SECONDS = 5 * 60
STACK_UPDATE_STATUS_SECONDS = 5

DEFAULT_WINDOW_WIDTH = 400
DEFAULT_WINDOW_HEIGHT = 640
MINIMUM_WINDOW_WIDTH = 400
MINIMUM_WINDOW_HEIGHT = 420

DEFAULT_GLOBAL_SHORTCUT = "Ctrl+Alt+Space"
AUTOSTART_VALUE_NAME = "Despatch"
IPC_SERVER_PREFIX = "gtvfx.despatch"
