"""Constants shared by Despatch modules."""

PRODUCT_NAME = "Despatch"
PRODUCT_VERSION = "0.1.0"
PRODUCT_DESCRIPTION = "Application launcher for Envoy-managed environments"
ORGANIZATION_NAME = "gtvfx-contrib"
ORGANIZATION_DOMAIN = "gtvfx-contrib.github.io"

MANIFEST_FILENAME = "despatch.json"
MANIFEST_SCHEMA_VERSION = 1
RESOURCE_ICONS_DIRECTORY = "resources/icons"
SETTINGS_SCHEMA_VERSION = 1
MAX_RECENT_APPLICATIONS = 20

DEFAULT_WINDOW_WIDTH = 720
DEFAULT_WINDOW_HEIGHT = 640
MINIMUM_WINDOW_WIDTH = 540
MINIMUM_WINDOW_HEIGHT = 420

DEFAULT_GLOBAL_SHORTCUT = "Ctrl+Alt+Space"
AUTOSTART_VALUE_NAME = "Despatch"
IPC_SERVER_PREFIX = "gtvfx.despatch"
